halozat.md létrehozása
arphox/tudasbazis pull request #14
Opened 2019-04-14 10:32 UTC by arphox

Főleg saját tudásból és webes forrásokból összerakott oldal.

Ezen a téren lehet, hogy nem elég széles a látóköröm így ha van "nagyon alap" dolog, amit kihagytam, szóljatok.

2019-04-14 12:29 UTC, ghost approved these changes
A későbbiekben érdemes még linkekkel bővíteni, de kezdetnek teljesen király :)

2019-04-16 11:07 UTC, zilahir requested changes
én az alapismeretes részt, ha már "alap" 1-2-3 mondattal kiegészíteném, hogy mik azok, legyen meg akkor egy helyen magyarul ez a tudás. a tcp/udp kliens-hez meg behúzni valamilyen egyszerű példát, valamilyen github repobol.

2019-04-16 11:20 UTC, arphox commented
> 
> 
> én az alapismeretes részt, ha már "alap" 1-2-3 mondattal kiegészíteném, hogy mik azok, legyen meg akkor egy helyen magyarul ez a tudás. a tcp/udp kliens-hez meg behúzni valamilyen egyszerű példát, valamilyen github repobol.

Részben egyetértek azzal, amit írsz, de alapvetően a repo nem tankönyv akar lenni hanem inkább egy vázlat. Ezek közül bármelyikre ráguglizok, találni fogok róla magyar nyelvű leírást.

Ezekben a dokumentumokban szerintem inkább az az érték, hogy ezeket a címszavakat együtt találod meg, és kapsz egy listát arról, hogy mi az amit "illene" tudni.

2019-04-16 11:22 UTC, zilahir commented
> > én az alapismeretes részt, ha már "alap" 1-2-3 mondattal kiegészíteném, hogy mik azok, legyen meg akkor egy helyen magyarul ez a tudás. a tcp/udp kliens-hez meg behúzni valamilyen egyszerű példát, valamilyen github repobol.
> 
> Részben egyetértek azzal, amit írsz, de alapvetően a repo nem tankönyv akar lenni hanem inkább egy vázlat. Ezek közül bármelyikre ráguglizok, találni fogok róla magyar nyelvű leírást.
> 
> Ezekben a dokumentumokban szerintem inkább az az érték, hogy ezeket a címszavakat együtt találod meg, és kapsz egy listát arról, hogy mi az amit "illene" tudni.

Igen, ez is igaz. :) Rendben akkor.

2019-04-16 11:22 UTC, zilahir approved these changes

2019-04-16 11:22 UTC, merged